name: barber_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1

  # Firebase Core
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.6

  # Authentication
  google_sign_in: ^6.2.1

  # Media & Images
  image_picker: ^1.1.2
  cached_network_image: ^3.3.0
  video_player: ^2.8.2
  chewie: ^1.7.0

  # Utilities
  intl: ^0.19.0
  http: ^1.1.0

  # Location & Maps
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/